"""
preprocess_crcd_for_sni.py — adapter from CRCD-Published format to SNI-SLAM
Replica-style input layout.

Input  (per snippet, e.g. F_1/snippet_002):
  <snippet>/rgb/frame_NNNNNN.png             (pre-rect left, PNG)
  <snippet>/rgbright/frame_NNNNNN.png        (pre-rect right, unused here but kept for parity)
  <snippet>/semantic_instance/frame_NNNNNN.png (uint8/16, values 0..3 per info_semantic.json)
  <snippet>/groundtruth.txt                  (TUM: timestamp tx ty tz qx qy qz qw, plus possible "#" header)

Output (SNI-SLAM Replica-style):
  <output>/rgb/rgb_NNNNNN.png                (rectified left, BGR uint8)
  <output>/semantic_class/semantic_class_NNNNNN.png  (rectified, uint8 0..3)
  <output>/traj.txt                          (16 floats per line, c2w in OpenCV/TUM frame —
                                              the dataset loader applies the OpenGL flip)

Note: DEPTH (depth/depth_NNNNNN.png at scale 10000) is generated by a separate
step (generate_depth_moge.py in the runbook). This script handles rgb, semantics,
poses, and the bound derivation only.

Bound derivation: read groundtruth.txt, take per-axis (x,y,z) min/max across all
GT translations, pad each axis by --pad_m (default 0.25 m), then emit the
SNI-SLAM yaml at the path passed by --emit_config. Bound is shared between
mapping.bound and mapping.marching_cubes_bound.

Usage:
  python sni-slam/Addons/preprocess/preprocess_crcd_for_sni.py \\
      --snippet_dir "F:/Datasets/CRCD-Published/F_1/snippet_002" \\
      --calib_pkl   "C:/Users/benli/sam3facebook/cam_cali/cam_calib/ECM_STEREO_1280x720_L2R_calib_data_opencv.pkl" \\
      --output_dir  "sni-slam/data/CRCD/F1_002" \\
      --emit_config "sni-slam/configs/CRCD/f1_002.yaml" \\
      --config_template "sni-slam/configs/CRCD/_template.yaml" \\
      --snippet_id F1_002

Frame indices in output start at 000000.
"""

import argparse
import os
import pickle
import sys

import cv2
import numpy as np
from scipy.spatial.transform import Rotation as R
from tqdm import tqdm


def load_stereo_maps(calib_pkl):
    # .npz path: the runbook exports the rectify maps to a numpy-version-agnostic
    # .npz when the source pkl is proto-5 / numpy>=2 (unreadable in the py3.7 env).
    if calib_pkl.endswith(".npz"):
        calib = np.load(calib_pkl)
    else:
        with open(calib_pkl, "rb") as f:
            calib = pickle.load(f)
    return {
        "map_left_x": calib["ecm_map_left_x"],
        "map_left_y": calib["ecm_map_left_y"],
    }


def parse_tum(path):
    rows = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            vals = list(map(float, line.split()))
            if len(vals) < 8:
                continue
            rows.append(vals[:8])
    return np.array(rows)


def tum_to_c2w(row):
    t = row[1:4]
    qx, qy, qz, qw = row[4:8]
    c2w = np.eye(4)
    c2w[:3, :3] = R.from_quat([qx, qy, qz, qw]).as_matrix()
    c2w[:3, 3] = t
    return c2w


def derive_bound(translations, pad_m):
    mn = translations.min(0) - pad_m
    mx = translations.max(0) + pad_m
    return [[float(mn[0]), float(mx[0])],
            [float(mn[1]), float(mx[1])],
            [float(mn[2]), float(mx[2])]]


CONFIG_TEMPLATE = """\
# Auto-generated by preprocess_crcd_for_sni.py for snippet {snippet_id}
# Bound = GT translation extent +/- {pad_m} m (see preprocess output).
inherit_from: configs/SNI-SLAM.yaml
dataset: 'crcd'
cam:
  H: 720
  W: 1280
  fx: 1096.6961889243337
  fy: 1096.6961889243337
  cx: 622.8076171875
  cy: 383.12598037719727
  png_depth_scale: 10000
  crop_edge: 0
mapping:
  bound: [[{x0:.4f},{x1:.4f}],[{y0:.4f},{y1:.4f}],[{z0:.4f},{z1:.4f}]]
  marching_cubes_bound: [[{x0:.4f},{x1:.4f}],[{y0:.4f},{y1:.4f}],[{z0:.4f},{z1:.4f}]]
model:
  cnn:
    n_classes: 4
func:
  use_gt_semantic: True
data:
  input_folder: data/CRCD/{snippet_id}/
  output: output/CRCD/{snippet_id}/test
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--snippet_dir", required=True)
    ap.add_argument("--calib_pkl", required=True)
    ap.add_argument("--output_dir", required=True)
    ap.add_argument("--emit_config", required=True, help="Path to write per-snippet yaml")
    ap.add_argument("--snippet_id", required=True, help="e.g. F1_002, C2_001, ...")
    ap.add_argument("--pad_m", type=float, default=0.25, help="bound padding in metres")
    args = ap.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    os.makedirs(os.path.join(args.output_dir, "rgb"), exist_ok=True)
    os.makedirs(os.path.join(args.output_dir, "semantic_class"), exist_ok=True)

    maps = load_stereo_maps(args.calib_pkl)

    rgb_dir = os.path.join(args.snippet_dir, "rgb")
    sem_dir = os.path.join(args.snippet_dir, "semantic_instance")
    gt_path = os.path.join(args.snippet_dir, "groundtruth.txt")

    rgb_files = sorted(f for f in os.listdir(rgb_dir) if f.endswith(".png"))
    print(f"[{args.snippet_id}] {len(rgb_files)} left frames")

    # 1. Parse GT, build c2w list (kept in OpenCV/TUM frame — loader flips)
    rows = parse_tum(gt_path)
    if len(rows) != len(rgb_files):
        print(f"[{args.snippet_id}] FATAL: gt rows={len(rows)} vs rgb files={len(rgb_files)} — "
              f"counts must match. Silently truncating would corrupt frame indexing in SNI-SLAM.")
        sys.exit(1)
    n = len(rgb_files)

    traj_lines = []
    translations = []
    for i in range(n):
        c2w = tum_to_c2w(rows[i])
        translations.append(c2w[:3, 3].copy())
        traj_lines.append(" ".join(f"{v:.10f}" for v in c2w.reshape(-1)))
    translations = np.array(translations)

    # 2. Bound
    bound = derive_bound(translations, args.pad_m)
    extent_mm = (translations.max(0) - translations.min(0)) * 1000
    print(f"[{args.snippet_id}] GT extent (mm): x={extent_mm[0]:.1f} y={extent_mm[1]:.1f} z={extent_mm[2]:.1f}")
    print(f"[{args.snippet_id}] bound (m, +/- {args.pad_m}): {bound}")

    # 3. Rectify rgb + semantic_instance
    for i in tqdm(range(n), desc=f"rectify {args.snippet_id}"):
        fname = rgb_files[i]
        l_in = os.path.join(rgb_dir, fname)
        l_img = cv2.imread(l_in)
        if l_img is None:
            print(f"  WARN: failed read {l_in}")
            continue
        l_rect = cv2.remap(l_img, maps["map_left_x"], maps["map_left_y"], cv2.INTER_LINEAR)
        cv2.imwrite(os.path.join(args.output_dir, "rgb", f"rgb_{i:06d}.png"), l_rect)

        sem_in = os.path.join(sem_dir, fname)
        if not os.path.isfile(sem_in):
            print(f"[{args.snippet_id}] FATAL: missing semantic_instance for {fname} — "
                  f"every rgb frame must have a paired semantic, else the SNI-SLAM "
                  f"loader's per-frame glob will misalign rgb/depth/sem indices.")
            sys.exit(1)
        sem = cv2.imread(sem_in, cv2.IMREAD_UNCHANGED)
        sem_rect = cv2.remap(sem, maps["map_left_x"], maps["map_left_y"], cv2.INTER_NEAREST)
        # CRCD info_semantic.json defines values 0..3. Anything outside that range
        # is data corruption — bail loudly rather than silently mod-256-truncate.
        vmin, vmax = int(sem_rect.min()), int(sem_rect.max())
        if vmin < 0 or vmax > 3:
            print(f"[{args.snippet_id}] FATAL: semantic values out of CRCD range "
                  f"[0..3] for {fname}: min={vmin} max={vmax} unique={np.unique(sem_rect)}")
            sys.exit(1)
        sem_rect = sem_rect.astype(np.uint8)
        cv2.imwrite(os.path.join(args.output_dir, "semantic_class", f"semantic_class_{i:06d}.png"), sem_rect)

    # 4. traj.txt — atomic write so a Ctrl-C between phases doesn't leave a
    # truncated file that the runbook's sentinel logic would treat as complete.
    traj_dst = os.path.join(args.output_dir, "traj.txt")
    traj_tmp = traj_dst + ".tmp"
    with open(traj_tmp, "w") as f:
        f.write("\n".join(traj_lines) + "\n")
    os.replace(traj_tmp, traj_dst)
    print(f"[{args.snippet_id}] wrote traj.txt with {n} poses")

    # 5. Emit per-snippet yaml — atomic write so a partial preprocess never
    # leaves run.py with half-a-config (which would crash deep into setup).
    os.makedirs(os.path.dirname(args.emit_config), exist_ok=True)
    yaml_text = CONFIG_TEMPLATE.format(
        snippet_id=args.snippet_id,
        pad_m=args.pad_m,
        x0=bound[0][0], x1=bound[0][1],
        y0=bound[1][0], y1=bound[1][1],
        z0=bound[2][0], z1=bound[2][1],
    )
    cfg_tmp = args.emit_config + ".tmp"
    with open(cfg_tmp, "w") as f:
        f.write(yaml_text)
    os.replace(cfg_tmp, args.emit_config)
    print(f"[{args.snippet_id}] emitted config: {args.emit_config}")

    print(f"\n[{args.snippet_id}] Done. Output at: {args.output_dir}")
    print(f"  rgb/             : {n} files")
    print(f"  semantic_class/  : {n} files (some may be missing if GT mask absent)")
    print(f"  traj.txt         : {n} lines")
    print(f"  bound            : x [{bound[0][0]:.3f},{bound[0][1]:.3f}]  "
          f"y [{bound[1][0]:.3f},{bound[1][1]:.3f}]  "
          f"z [{bound[2][0]:.3f},{bound[2][1]:.3f}]")


if __name__ == "__main__":
    main()
